spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_LOGIN}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /USAINUA_Admin

#logging:
#  config: classpath:logback.xml


#  tomcat:
#    accesslog:
#      enabled: true
#      directory: USAINUA_Admin
#      pattern: common
#      suffix: .log
#      prefix: logs
#      file-date-format: .yyyy-MM-dd
#    basedir: logging
#logging:
#  file:
#    path: /logging/USAINUA_Admin/
#    name: logback.txt