name: Deploy to Tomcat
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2
      - name: Build the project
        run: |
          mvn package
          mvn war:war
      - name: Deploy to Tomcat
        run: |
          curl -T target/USAINUA_Admin.war -u tomcat:OUlIg40qOZ "http://kino.avada-media-dev1.od.ua/manager/html/deploy?path=/USAINUA_Admin&update=true"