name: Deploy to Tomcat
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
      - name: Build the project
        run: |
          mvn package -DskipTests=true
          mvn war:war
      - name: Update application.yaml
        run: |
          sed -i -e 's|${DB_URL}|${{ secrets.DB_URL }}|g' target/USAINUA_Admin/WEB-INF/classes/application.yaml
          sed -i -e 's|${DB_LOGIN}|${{ secrets.DB_LOGIN }}|g' target/USAINUA_Admin/WEB-INF/classes/application.yaml
          sed -i -e 's|${DB_PASSWORD}|${{ secrets.DB_PASSWORD }}|g' target/USAINUA_Admin/WEB-INF/classes/application.yaml
      - name: Copy folder
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/USAINUA_Admin
          remote: tomcat/webapps/USAINUA_Admin
          host: ${{ secrets.SSH_URL }}
          username: ${{ secrets.SSH_LOGIN }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: Copy file
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/USAINUA_Admin.war
          remote: tomcat/webapps/USAINUA_Admin.war
          host: ${{ secrets.SSH_URL }}
          username: ${{ secrets.SSH_LOGIN }}
          password: ${{ secrets.SSH_PASSWORD }}
