name: Deploy to Tomcat
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
      - name: Build the project
        run: |
          mvn package
#          mvn war:war
      - name: Copy folder
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/USAINUA_Admin
          remote: tomcat/webapps/USAINUA_Admin
          host: kino.avada-media-dev1.od.ua
          username: avada_kino
          password: "#Es84!4lZ0P7"
      - name: Copy file
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/USAINUA_Admin.war
          remote: tomcat/webapps/USAINUA_Admin.war
          host: kino.avada-media-dev1.od.ua
          username: avada_kino
          password: "#Es84!4lZ0P7"